import React from "react";
import Head from "next/head";
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Scriptorium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="py-16">
          <div className="container mx-auto px-6 text-center">
            <h1 className="text-4xl font-bold text-cyan-400 mb-2">
              Welcome to Scriptorium!
            </h1>
            <p className="text-xl text-fuchsia-500 mb-6">
               The new way of writing codes.
            </p>
            <button className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 transition duration-300" 
            onClick={() => router.push('/register')}>
              Get Started
            </button>
          </div>
          <div className="container mx-auto px-6 mt-12 grid gap-8 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
  <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center text-indigo-700">
    <h2 className="text-2xl font-semibold mb-2">Powerful code compilation</h2>
    <p className="text-gray-700">
    <img src="/feature-one.png" alt="Feature One" className="mx-auto mb-4 w-50 h-50" />
      Compile and run code, supporting over 10+ programming languages.
    </p>
  </div>
  <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center text-indigo-700">
    <h2 className="text-2xl font-semibold mb-2">Code Templates at your fingertips</h2>
    <p className="text-gray-700">
    <img src="/feature-two.png" alt="Feature Two" className="mx-auto mb-4 w-50 h-50" />
      Save and publish your code as code templates where you can share code with other users all in one place.
    </p>
  </div>
  <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center text-indigo-700">
    
    <h2 className="text-2xl font-semibold mb-2">Thriving community</h2>
    <p className="text-gray-700">
    <img src="/feature-three.png" alt="Feature Three" className="mx-auto mb-4 w-50 h-50" />
      Join in an active community where you can discuss, share ideas, and vote on important topics.
    </p>
  </div>
</div>

        </section>
      </main>
    </>
  );
}

